name: Test Actions (push)
on:
  push:
    branches: [ "main" ]
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello and show context
        run: |
          echo "✅ Workflow сработал!"
          echo "📦 Репозиторий: $GITHUB_REPOSITORY"
          echo "🌿 Ветка: $GITHUB_REF_NAME"
          echo "🔖 Коммит: $GITHUB_SHA"
          echo "🕒 Время: $(date -u) UTC"
